/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
title: Need some space?
*/

import React, { useRef } from "react";
import { Canvas, useFrame, useLoader } from "@react-three/fiber";
import { OrbitControls, useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/files/galaxy.gltf");
  useFrame(() => {
    // group.current.rotation.y -= 0.01;
  });
  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
          <points
            geometry={nodes.Object_2.geometry}
            material={nodes.Object_2.material}
          />
        </group>
      </group>
      {/* <OrbitControls /> */}
    </>
  );
}

useGLTF.preload("/files/galaxy.gltf");
