import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import PageHeader from "../components/PageHeader";
import HomeCanvas from "../components/Canvas/HomeCanvas";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Platform - Digital Marketing</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <PageHeader />
        </main>
      </div>
      <div
        style={{
          width: "100vw",
          height: "100vh",
          position: "fixed",
          top: 0,
          zIndex: "-1",
        }}
      >
        <HomeCanvas />
      </div>
    </>
  );
}
